name: Xcode - Build and Publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and publish
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          workspace: Textual.xcworkspace
          scheme: "Textual (Standard Release)"
          destination: platform=macOS
          action: build
      - name: List files
        run: |
          ls -al .
